### ISSUE TITLE
Documentation not clear on worker re-use

### ISSUE THREAD

**Issue by bsutton** [iandis/isolated_worker#16]
The documentation doesn't cover off if a IsolatedWorker is re-usable.

**Comment by iandis** [comment]
Hi, did you mean `IsolatedWorker` instance is able to be created or whether it is singleton or not? Please let me know if there's some context here I'm missing.

**Comment by bsutton** [comment]
So looking for clarity in the doco on how you fire off multiple jobs.

Can you re-use the worker or do you need to create a new one each time?

Can you run multiple jobs with the same worker simultaneously?

**Comment by iandis** [comment]
I think the docs have stated it clearly, that it spawns a **singleton** instance of worker. And about the multiple jobs, because it's Isolate/Web Worker, it is possible.

**Comment by bsutton** [comment]
Hmm, that fact that I'm asking suggests that the documentation doesn't
contain sufficient info.

Just add some examples of reusing a worker so it's clear how to use it.


S. Brett Sutton
Noojee Contact Solutions
03 8320 8100

**Comment by bsutton** [comment]
Some more thought on this.

The problem is that it doesn't detail how it manages isolates.

Does it's use a single isolate, a pool of isolates or does it start
isolates as required?

If it uses multiple isolates how are they managed?

Will it start a thousand isolates if i do a thousand runs or does it limit
the pool.

Does it reuse isolates or start a new isolate each time.

These are important consideration when choosing and using an isolate
package as the can have considerable impact on performance.

**Comment by iandis** [comment]
I'm pretty sure it's already stated in the docs [here](https://pub.dev/documentation/isolated_worker/latest/isolated_worker/IsolatedWorker-class.html) and [here](https://pub.dev/documentation/isolated_worker/latest/isolated_worker/IsolatedWorker/IsolatedWorker.html). It clearly states that it is a **singleton** spawning a **single** Isolate.

**Comment by bsutton** [comment]
The fact that it is a singleton tells the reader nothing about how isolates
are managed under the hood.
