### ISSUE TITLE
Bidirectional Communication with worker

### ISSUE THREAD

**Issue by yashhema** [iandis/isolated_worker#18]
Hello,
Is it possible to have bidirectional communication with the worker . I want to use isolate for Firebase Query listener, it needs to reply back the messages and also I need to shut down the listener or change its parameter on go

regard

**Comment by iandis** [comment]
Hi, for that kind of use-case I'd recommend you to use `Isolate` instead as this package is just to cover similar use-case to the `compute` function using a single long-lived `Isolate`
