### ISSUE TITLE
isolate_worker is not working for web

### ISSUE THREAD

**Issue by smartaslst** [iandis/isolated_worker#19]
IsolatedWorker().run(sum, 1000).then(value) {
   print(s)
}

int sum(int a) {
  int s = 0;
  for (int i = 0; i < a; i++) {
     s = s + i;
  }

  return s;
}

This code is working well for mobile.
But not for web.
I don't use same code for both mobile and web.
Please help me

**Comment by scrtkr** [comment]
for web, should use JsIsolatedWorker

**Comment by iandis** [comment]
Closing this as you should use `JsIsolatedWorker` on web as mentioned above.
