### ISSUE TITLE
Hello, can u help!?)

### ISSUE THREAD

**Issue by NickKoroloff** [iandis/isolated_worker#2]
Thanks for the written package.
Could you please provide more examples for the flutter WEB on how to work correctly with this API? just simple examples)

**Comment by iandis** [comment]
Hi thank you for your feedback.
I'll update README regarding the Flutter Web example. Thank you.

**Comment by NickKoroloff** [comment]
Big thx !! Happy fluttering ;)

**Comment by iandis** [comment]
You can now check out the example as the new patch has been released. Thank you.
