### ISSUE TITLE
DB operation using moor within JsIsolatedWorker

### ISSUE THREAD

**Issue by KiraKmp** [iandis/isolated_worker#6]
Hi, i am using moor for DB in my application, is it possible to use moor DB connection within JsIsolatedWorker, any alternate ways to establish DB connection in JsIsolatedWorker.

**Comment by iandis** [comment]
Hi, though I haven't used Moor for DB related things, but at a first glance I think it's _possible_ since it depends on a native JS library (sql.js) which is compatible with `JsIsolatedWorker`. However for now I'm not really sure, so I might be trying it this weekend.

**Comment by KiraKmp** [comment]
Thank you for your fast reply and trying it out, It would be great if we can get this done, which would add more value to this package.

**Comment by iandis** [comment]
Hi, if you're curious about the progress, check out my template repo [here](https://github.com/iandis/moor_shared)
It's currently at the stage of trying to find a workaround for [Prepared Statements](https://sql.js.org/documentation/Statement.html) as it is used by operations like select and batch. Thank you.

**Comment by iandis** [comment]
Closing this as the example of moor web + JsIsolatedWorker is [answered](https://github.com/iandis/isolated_worker/issues/6#issuecomment-930119558)
